// Synthetic preview/terminal content; no connections to real Shells.
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-gpu']});
try{
 const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];let connections=0,inputs=0;
 await page.addInitScript(()=>{
  const start=document.startViewTransition.bind(document);
  window.themeTransitions=0;
  document.startViewTransition=update=>{window.themeTransitions++;return window.lastThemeTransition=start(update);};
 });
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/snapshot',r=>r.fulfill({status:404,body:''}));
 await page.routeWebSocket('**/pty?*',ws=>{
  connections++;ws.onMessage(m=>{if(JSON.parse(String(m)).type==='input')inputs++;});
  ws.send(JSON.stringify({type:'ready',pid:1}));ws.send(Buffer.from('~/project $ git status\r\nOn branch main\r\nWorking tree clean\r\n'));
 });
 await page.goto(process.env.POC_URL||'http://127.0.0.1:4389');
 await page.waitForFunction(()=>document.querySelectorAll('.pane-body[data-connected="true"]').length===4);
 await page.locator('.pane-body').first().click();
 await page.keyboard.press('Control+Shift+Y');
 await page.getByRole('button',{name:'Showcase',exact:true}).click();
 assert.equal(await page.locator('.showcase-card').count(),3);
 const initial=connections;
 await page.getByRole('button',{name:'Next theme',exact:true}).click();
 assert.equal(await page.locator('#showcase-name').textContent(),'Catppuccin');
 await page.keyboard.press('ArrowRight');
 assert.equal(await page.locator('#showcase-name').textContent(),'Catppuccin Latte');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'boomux','browsing is preview only');
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#theme-dialog').evaluate(d=>d.open),false);
 await page.waitForFunction(()=>document.activeElement===document.querySelector('#theme-picker'));
 await page.getByRole('button',{name:'Choose theme',exact:true}).click();
 assert.equal(await page.locator('#showcase-name').textContent(),'Boomux','cancel restores selection');
 await page.getByRole('button',{name:'Next theme',exact:true}).click();
 await page.keyboard.press('Enter');
 await page.evaluate(async()=>{await window.lastThemeTransition.ready;
  const wipe=document.getAnimations().find(a=>a.animationName==='boomux-theme-reveal');
  if(!wipe)throw Error('Diagonal wipe did not start');wipe.pause();wipe.currentTime=130;
 });
 await page.screenshot({path:'/tmp/boomux-theme-wipe.png'});
 await page.evaluate(async()=>{document.getAnimations().find(a=>a.animationName==='boomux-theme-reveal').play();await window.lastThemeTransition.finished;});
 assert.equal(await page.locator('html').getAttribute('data-theme'),'catppuccin');
 assert.equal(connections,initial);assert.equal(inputs,0,'picker keyboard does not type into Shells');
 await page.getByRole('button',{name:'Choose theme',exact:true}).click();
 await page.getByRole('button',{name:'List view',exact:true}).click();
 assert.equal(await page.locator('.theme-list').isVisible(),true);
 await page.getByRole('button',{name:'Showcase',exact:true}).click();
 await page.waitForTimeout(300);
 await page.screenshot({path:'/tmp/boomux-theme-showcase.png'});
 await page.setViewportSize({width:600,height:850});
 const dialog=await page.locator('#theme-dialog').boundingBox();
 assert.ok(dialog.x>=0&&dialog.x+dialog.width<=601,'showcase fits narrow viewport');
 assert.equal(await page.getByRole('button',{name:'Apply theme',exact:true}).isVisible(),true);
 await page.keyboard.press('Escape');
 await page.goto((process.env.POC_URL||'http://127.0.0.1:4389')+'/?theme-showcase');
 assert.equal(await page.locator('#theme-dialog').evaluate(d=>d.open),true,'recording link opens showcase');
 await page.emulateMedia({reducedMotion:'reduce'});
 const count=await page.evaluate(()=>window.themeTransitions);
 await page.getByRole('button',{name:'Next theme',exact:true}).click();
 await page.getByRole('button',{name:'Apply theme',exact:true}).click();
 assert.equal(await page.evaluate(()=>window.themeTransitions),count,'reduced motion applies without a wipe');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'catppuccin-latte');
 await page.setViewportSize({width:1600,height:1000});
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.evaluate(()=>{document.startViewTransition=undefined;});
 await page.getByRole('button',{name:'Choose theme',exact:true}).click();
 await page.getByRole('button',{name:'Next theme',exact:true}).click();
 await page.getByRole('button',{name:'Apply theme',exact:true}).click();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'ethereal','unsupported browsers apply directly');
 await page.keyboard.press('Control+Shift+Y');
 await page.getByRole('button',{name:'List view',exact:true}).click();
 await page.getByRole('button',{name:'Nord',exact:true}).click();
 await page.keyboard.press('Enter');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'nord','Enter applies list selection');
 await page.keyboard.press('Control+Shift+Y');
 assert.equal(await page.locator('#theme-dialog').evaluate(d=>d.open),true);
 await page.keyboard.press('Control+Shift+Y');
 assert.equal(await page.locator('#theme-dialog').evaluate(d=>d.open),false,'shortcut toggles picker');
 assert.equal(inputs,0,'theme shortcuts and Enter never reach Shells');
 assert.deepEqual(errors,[]);
 console.log('Showcase browsing, cancel/apply, focus, preserved attachments, list toggle, narrow viewport, recording link, diagonal wipe, reduced motion, and unsupported-browser fallback passed');
}finally{await browser.close();}
