// Palettes derived from omacom/omarchy themes/*/colors.toml (MIT).
// See THIRD_PARTY_NOTICES.md for the pinned source and license.
export const themes=[
  {
    "id": "boomux",
    "name": "Boomux",
    "bg": "#13171c",
    "deep": "#101218",
    "surface": "#181a1e",
    "raised": "#242830",
    "border": "#303b42",
    "fg": "#c9d4e8",
    "muted": "#8e99ab",
    "accent": "#91b8b0",
    "selection": "#405478",
    "light": false,
    "terminal": {
      "background": "#13171c",
      "foreground": "#c9d4e8",
      "cursor": "#a9b9ff",
      "selectionBackground": "#405478",
      "black": "#161b24",
      "red": "#ed929b",
      "green": "#8bc6ac",
      "yellow": "#e1b889",
      "blue": "#8cafd7",
      "magenta": "#b4a2e5",
      "cyan": "#83c6ce",
      "white": "#c9d4e8",
      "brightBlack": "#65738b",
      "brightRed": "#f14c4c",
      "brightGreen": "#23d18b",
      "brightYellow": "#f5f543",
      "brightBlue": "#3b8eea",
      "brightMagenta": "#d670d6",
      "brightCyan": "#29b8db",
      "brightWhite": "#ffffff"
    }
  },
  {
    "id": "catppuccin",
    "name": "Catppuccin",
    "light": false,
    "bg": "#1e1e2e",
    "deep": "#101019",
    "surface": "#161622",
    "raised": "#313244",
    "border": "#585b70",
    "fg": "#cdd6f4",
    "muted": "#bac2de",
    "accent": "#89b4fa",
    "selection": "#45475a",
    "terminal": {
      "background": "#1e1e2e",
      "foreground": "#cdd6f4",
      "cursor": "#cdd6f4",
      "selectionBackground": "#45475a",
      "black": "#1e1e2e",
      "white": "#cdd6f4",
      "brightBlack": "#585b70",
      "brightWhite": "#cdd6f4",
      "red": "#f38ba8",
      "brightRed": "#f38ba8",
      "green": "#a6e3a1",
      "brightGreen": "#a6e3a1",
      "yellow": "#f9e2af",
      "brightYellow": "#f9e2af",
      "blue": "#89b4fa",
      "brightBlue": "#89b4fa",
      "magenta": "#f5c2e7",
      "brightMagenta": "#f5c2e7",
      "cyan": "#94e2d5",
      "brightCyan": "#94e2d5"
    }
  },
  {
    "id": "catppuccin-latte",
    "name": "Catppuccin Latte",
    "light": true,
    "bg": "#eff1f5",
    "deep": "#d7d8dc",
    "surface": "#e3e4e8",
    "raised": "#dce0e8",
    "border": "#acb0be",
    "fg": "#4c4f69",
    "muted": "#5c5f77",
    "accent": "#1e66f5",
    "selection": "#ccd0da",
    "terminal": {
      "background": "#eff1f5",
      "foreground": "#4c4f69",
      "cursor": "#4c4f69",
      "selectionBackground": "#ccd0da",
      "black": "#eff1f5",
      "white": "#4c4f69",
      "brightBlack": "#acb0be",
      "brightWhite": "#4c4f69",
      "red": "#d20f39",
      "brightRed": "#d20f39",
      "green": "#40a02b",
      "brightGreen": "#40a02b",
      "yellow": "#df8e1d",
      "brightYellow": "#df8e1d",
      "blue": "#1e66f5",
      "brightBlue": "#1e66f5",
      "magenta": "#ea76cb",
      "brightMagenta": "#ea76cb",
      "cyan": "#179299",
      "brightCyan": "#179299"
    }
  },
  {
    "id": "ethereal",
    "name": "Ethereal",
    "light": false,
    "bg": "#060B1E",
    "deep": "#030610",
    "surface": "#040816",
    "raised": "#131a3a",
    "border": "#6d7db6",
    "fg": "#ffcead",
    "muted": "#c9b8a6",
    "accent": "#7d82d9",
    "selection": "#252e56",
    "terminal": {
      "background": "#060B1E",
      "foreground": "#ffcead",
      "cursor": "#ffcead",
      "selectionBackground": "#252e56",
      "black": "#060B1E",
      "white": "#ffcead",
      "brightBlack": "#6d7db6",
      "brightWhite": "#ffcead",
      "red": "#ED5B5A",
      "brightRed": "#faaaa9",
      "green": "#92a593",
      "brightGreen": "#c4cfc4",
      "yellow": "#E9BB4F",
      "brightYellow": "#f7dc9c",
      "blue": "#7d82d9",
      "brightBlue": "#c2c4f0",
      "magenta": "#c89dc1",
      "brightMagenta": "#ead7e7",
      "cyan": "#a3bfd1",
      "brightCyan": "#dfeaf0"
    }
  },
  {
    "id": "everforest",
    "name": "Everforest",
    "light": false,
    "bg": "#2d353b",
    "deep": "#181d20",
    "surface": "#21272c",
    "raised": "#343f44",
    "border": "#475258",
    "fg": "#d3c6aa",
    "muted": "#9da9a0",
    "accent": "#7fbbb3",
    "selection": "#3d484d",
    "terminal": {
      "background": "#2d353b",
      "foreground": "#d3c6aa",
      "cursor": "#d3c6aa",
      "selectionBackground": "#3d484d",
      "black": "#2d353b",
      "white": "#d3c6aa",
      "brightBlack": "#475258",
      "brightWhite": "#d3c6aa",
      "red": "#e67e80",
      "brightRed": "#e67e80",
      "green": "#a7c080",
      "brightGreen": "#a7c080",
      "yellow": "#dbbc7f",
      "brightYellow": "#dbbc7f",
      "blue": "#7fbbb3",
      "brightBlue": "#7fbbb3",
      "magenta": "#d699b6",
      "brightMagenta": "#d699b6",
      "cyan": "#83c092",
      "brightCyan": "#83c092"
    }
  },
  {
    "id": "flexoki-light",
    "name": "Flexoki Light",
    "light": true,
    "bg": "#FFFCF0",
    "deep": "#e5e2d8",
    "surface": "#f2efe4",
    "raised": "#E6E4D9",
    "border": "#B7B5AC",
    "fg": "#100F0F",
    "muted": "#403E3C",
    "accent": "#205EA6",
    "selection": "#CECDC3",
    "terminal": {
      "background": "#FFFCF0",
      "foreground": "#100F0F",
      "cursor": "#100F0F",
      "selectionBackground": "#CECDC3",
      "black": "#FFFCF0",
      "white": "#100F0F",
      "brightBlack": "#B7B5AC",
      "brightWhite": "#100F0F",
      "red": "#D14D41",
      "brightRed": "#D14D41",
      "green": "#879A39",
      "brightGreen": "#879A39",
      "yellow": "#D0A215",
      "brightYellow": "#D0A215",
      "blue": "#205EA6",
      "brightBlue": "#4385BE",
      "magenta": "#CE5D97",
      "brightMagenta": "#CE5D97",
      "cyan": "#3AA99F",
      "brightCyan": "#3AA99F"
    }
  },
  {
    "id": "gruvbox",
    "name": "Gruvbox",
    "light": false,
    "bg": "#282828",
    "deep": "#161616",
    "surface": "#1e1e1e",
    "raised": "#3c3836",
    "border": "#665c54",
    "fg": "#d4be98",
    "muted": "#bdae93",
    "accent": "#7daea3",
    "selection": "#504945",
    "terminal": {
      "background": "#282828",
      "foreground": "#d4be98",
      "cursor": "#d4be98",
      "selectionBackground": "#504945",
      "black": "#282828",
      "white": "#d4be98",
      "brightBlack": "#665c54",
      "brightWhite": "#d4be98",
      "red": "#ea6962",
      "brightRed": "#ea6962",
      "green": "#a9b665",
      "brightGreen": "#a9b665",
      "yellow": "#d8a657",
      "brightYellow": "#d8a657",
      "blue": "#7daea3",
      "brightBlue": "#7daea3",
      "magenta": "#d3869b",
      "brightMagenta": "#d3869b",
      "cyan": "#89b482",
      "brightCyan": "#89b482"
    }
  },
  {
    "id": "hackerman",
    "name": "Hackerman",
    "light": false,
    "bg": "#0B0C16",
    "deep": "#06060c",
    "surface": "#080910",
    "raised": "#151828",
    "border": "#2d3450",
    "fg": "#ddf7ff",
    "muted": "#b5c5db",
    "accent": "#82FB9C",
    "selection": "#1f253a",
    "terminal": {
      "background": "#0B0C16",
      "foreground": "#ddf7ff",
      "cursor": "#ddf7ff",
      "selectionBackground": "#1f253a",
      "black": "#0B0C16",
      "white": "#ddf7ff",
      "brightBlack": "#2d3450",
      "brightWhite": "#ddf7ff",
      "red": "#50f872",
      "brightRed": "#85ff9d",
      "green": "#4fe88f",
      "brightGreen": "#9cf7c2",
      "yellow": "#50f7d4",
      "brightYellow": "#a4ffec",
      "blue": "#829dd4",
      "brightBlue": "#c4d2ed",
      "magenta": "#86a7df",
      "brightMagenta": "#cddbf4",
      "cyan": "#7cf8f7",
      "brightCyan": "#d1fffe"
    }
  },
  {
    "id": "kanagawa",
    "name": "Kanagawa",
    "light": false,
    "bg": "#1f1f28",
    "deep": "#111116",
    "surface": "#17171e",
    "raised": "#223249",
    "border": "#54546D",
    "fg": "#dcd7ba",
    "muted": "#c8c093",
    "accent": "#dcd7ba",
    "selection": "#363646",
    "terminal": {
      "background": "#1f1f28",
      "foreground": "#dcd7ba",
      "cursor": "#dcd7ba",
      "selectionBackground": "#363646",
      "black": "#1f1f28",
      "white": "#dcd7ba",
      "brightBlack": "#54546D",
      "brightWhite": "#dcd7ba",
      "red": "#c34043",
      "brightRed": "#e82424",
      "green": "#76946a",
      "brightGreen": "#98bb6c",
      "yellow": "#c0a36e",
      "brightYellow": "#e6c384",
      "blue": "#7e9cd8",
      "brightBlue": "#7fb4ca",
      "magenta": "#957fb8",
      "brightMagenta": "#938aa9",
      "cyan": "#6a9589",
      "brightCyan": "#7aa89f"
    }
  },
  {
    "id": "last-horizon",
    "name": "Last Horizon",
    "light": false,
    "bg": "#0c0b0c",
    "deep": "#060606",
    "surface": "#090809",
    "raised": "#0c0b0c",
    "border": "#584e51",
    "fg": "#FAFCFB",
    "muted": "#cfd3cd",
    "accent": "#b59790",
    "selection": "#584e51",
    "terminal": {
      "background": "#0c0b0c",
      "foreground": "#FAFCFB",
      "cursor": "#e2dddc",
      "selectionBackground": "#584e51",
      "black": "#0c0b0c",
      "white": "#FAFCFB",
      "brightBlack": "#584e51",
      "brightWhite": "#e2dddc",
      "red": "#c38b7b",
      "brightRed": "#c38b7b",
      "green": "#87a9b0",
      "brightGreen": "#87a9b0",
      "yellow": "#6B5E73",
      "brightYellow": "#6B5E73",
      "blue": "#b59790",
      "brightBlue": "#b59790",
      "magenta": "#c4d8e2",
      "brightMagenta": "#c4d8e2",
      "cyan": "#a5a0b6",
      "brightCyan": "#a5a0b6"
    }
  },
  {
    "id": "lumon",
    "name": "Lumon",
    "light": false,
    "bg": "#16242d",
    "deep": "#0b1216",
    "surface": "#101b21",
    "raised": "#1b2d40",
    "border": "#304860",
    "fg": "#d6e2ee",
    "muted": "#d6e2ee",
    "accent": "#8bc9eb",
    "selection": "#243d56",
    "terminal": {
      "background": "#16242d",
      "foreground": "#d6e2ee",
      "cursor": "#f2fcff",
      "selectionBackground": "#243d56",
      "black": "#16242d",
      "white": "#d6e2ee",
      "brightBlack": "#304860",
      "brightWhite": "#f2fcff",
      "red": "#4d86b0",
      "brightRed": "#73a6cb",
      "green": "#5e95bc",
      "brightGreen": "#86b7d8",
      "yellow": "#6fa4c9",
      "brightYellow": "#9dcae5",
      "blue": "#6fb8e3",
      "brightBlue": "#f2fcff",
      "magenta": "#8bc9eb",
      "brightMagenta": "#b1d8ee",
      "cyan": "#b4e4f6",
      "brightCyan": "#d1eef8"
    }
  },
  {
    "id": "lupine",
    "name": "Lupine",
    "light": true,
    "bg": "#fafafa",
    "deep": "#dedede",
    "surface": "#ececec",
    "raised": "#f5f5f5",
    "border": "#9e9e9e",
    "fg": "#212121",
    "muted": "#424242",
    "accent": "#3264eb",
    "selection": "#d0d0d0",
    "terminal": {
      "background": "#fafafa",
      "foreground": "#212121",
      "cursor": "#000000",
      "selectionBackground": "#d0d0d0",
      "black": "#fafafa",
      "white": "#212121",
      "brightBlack": "#9e9e9e",
      "brightWhite": "#000000",
      "red": "#c900c4",
      "brightRed": "#f930fb",
      "green": "#4a2fd0",
      "brightGreen": "#9f85e0",
      "yellow": "#026fde",
      "brightYellow": "#358fff",
      "blue": "#3264eb",
      "brightBlue": "#5482ff",
      "magenta": "#8a4ad7",
      "brightMagenta": "#b363ff",
      "cyan": "#0c67de",
      "brightCyan": "#3986ff"
    }
  },
  {
    "id": "matte-black",
    "name": "Matte Black",
    "light": false,
    "bg": "#121212",
    "deep": "#090909",
    "surface": "#0d0d0d",
    "raised": "#1e1e1e",
    "border": "#333333",
    "fg": "#bebebe",
    "muted": "#8a8a8d",
    "accent": "#e68e0d",
    "selection": "#2a2a2a",
    "terminal": {
      "background": "#121212",
      "foreground": "#bebebe",
      "cursor": "#bebebe",
      "selectionBackground": "#2a2a2a",
      "black": "#121212",
      "white": "#bebebe",
      "brightBlack": "#333333",
      "brightWhite": "#bebebe",
      "red": "#D35F5F",
      "brightRed": "#B91C1C",
      "green": "#FFC107",
      "brightGreen": "#FFC107",
      "yellow": "#b91c1c",
      "brightYellow": "#b90a0a",
      "blue": "#e68e0d",
      "brightBlue": "#f59e0b",
      "magenta": "#D35F5F",
      "brightMagenta": "#B91C1C",
      "cyan": "#bebebe",
      "brightCyan": "#eaeaea"
    }
  },
  {
    "id": "miasma",
    "name": "Miasma",
    "light": false,
    "bg": "#222222",
    "deep": "#121212",
    "surface": "#191919",
    "raised": "#2c2c2c",
    "border": "#666666",
    "fg": "#c2c2b0",
    "muted": "#8a8a7e",
    "accent": "#78824b",
    "selection": "#383838",
    "terminal": {
      "background": "#222222",
      "foreground": "#c2c2b0",
      "cursor": "#c2c2b0",
      "selectionBackground": "#383838",
      "black": "#222222",
      "white": "#c2c2b0",
      "brightBlack": "#666666",
      "brightWhite": "#c2c2b0",
      "red": "#685742",
      "brightRed": "#685742",
      "green": "#5f875f",
      "brightGreen": "#5f875f",
      "yellow": "#b36d43",
      "brightYellow": "#b36d43",
      "blue": "#78824b",
      "brightBlue": "#78824b",
      "magenta": "#bb7744",
      "brightMagenta": "#bb7744",
      "cyan": "#c9a554",
      "brightCyan": "#c9a554"
    }
  },
  {
    "id": "nord",
    "name": "Nord",
    "light": false,
    "bg": "#2e3440",
    "deep": "#191c23",
    "surface": "#222730",
    "raised": "#3b4252",
    "border": "#4c566a",
    "fg": "#d8dee9",
    "muted": "#adb5c4",
    "accent": "#81a1c1",
    "selection": "#434c5e",
    "terminal": {
      "background": "#2e3440",
      "foreground": "#d8dee9",
      "cursor": "#d8dee9",
      "selectionBackground": "#434c5e",
      "black": "#2e3440",
      "white": "#d8dee9",
      "brightBlack": "#4c566a",
      "brightWhite": "#d8dee9",
      "red": "#bf616a",
      "brightRed": "#bf616a",
      "green": "#a3be8c",
      "brightGreen": "#a3be8c",
      "yellow": "#ebcb8b",
      "brightYellow": "#ebcb8b",
      "blue": "#81a1c1",
      "brightBlue": "#81a1c1",
      "magenta": "#b48ead",
      "brightMagenta": "#b48ead",
      "cyan": "#88c0d0",
      "brightCyan": "#8fbcbb"
    }
  },
  {
    "id": "osaka-jade",
    "name": "Osaka Jade",
    "light": false,
    "bg": "#111c18",
    "deep": "#090f0d",
    "surface": "#0c1512",
    "raised": "#23372B",
    "border": "#53685B",
    "fg": "#C1C497",
    "muted": "#D6D5BC",
    "accent": "#509475",
    "selection": "#32473B",
    "terminal": {
      "background": "#111c18",
      "foreground": "#C1C497",
      "cursor": "#F7E8B2",
      "selectionBackground": "#32473B",
      "black": "#111c18",
      "white": "#C1C497",
      "brightBlack": "#53685B",
      "brightWhite": "#F7E8B2",
      "red": "#FF5345",
      "brightRed": "#db9f9c",
      "green": "#549e6a",
      "brightGreen": "#63b07a",
      "yellow": "#459451",
      "brightYellow": "#E5C736",
      "blue": "#509475",
      "brightBlue": "#ACD4CF",
      "magenta": "#D2689C",
      "brightMagenta": "#75bbb3",
      "cyan": "#2DD5B7",
      "brightCyan": "#8CD3CB"
    }
  },
  {
    "id": "retro-82",
    "name": "Retro 82",
    "light": false,
    "bg": "#05182e",
    "deep": "#020c17",
    "surface": "#031222",
    "raised": "#0a2540",
    "border": "#2a6b78",
    "fg": "#f6dcac",
    "muted": "#a7c9c6",
    "accent": "#faa968",
    "selection": "#134e5a",
    "terminal": {
      "background": "#05182e",
      "foreground": "#f6dcac",
      "cursor": "#f6dcac",
      "selectionBackground": "#134e5a",
      "black": "#05182e",
      "white": "#f6dcac",
      "brightBlack": "#2a6b78",
      "brightWhite": "#f6dcac",
      "red": "#f85525",
      "brightRed": "#f85525",
      "green": "#028391",
      "brightGreen": "#028391",
      "yellow": "#e97b3c",
      "brightYellow": "#e97b3c",
      "blue": "#3f8f8a",
      "brightBlue": "#faa968",
      "magenta": "#3f8f8a",
      "brightMagenta": "#3f8f8a",
      "cyan": "#8cbfb8",
      "brightCyan": "#8cbfb8"
    }
  },
  {
    "id": "ristretto",
    "name": "Ristretto",
    "light": false,
    "bg": "#2c2525",
    "deep": "#181414",
    "surface": "#211b1b",
    "raised": "#3d2f2a",
    "border": "#72696a",
    "fg": "#e6d9db",
    "muted": "#c3b7b8",
    "accent": "#f38d70",
    "selection": "#403e41",
    "terminal": {
      "background": "#2c2525",
      "foreground": "#e6d9db",
      "cursor": "#e6d9db",
      "selectionBackground": "#403e41",
      "black": "#2c2525",
      "white": "#e6d9db",
      "brightBlack": "#72696a",
      "brightWhite": "#e6d9db",
      "red": "#fd6883",
      "brightRed": "#ff8297",
      "green": "#adda78",
      "brightGreen": "#c8e292",
      "yellow": "#f9cc6c",
      "brightYellow": "#fcd675",
      "blue": "#f38d70",
      "brightBlue": "#f8a788",
      "magenta": "#a8a9eb",
      "brightMagenta": "#bebffd",
      "cyan": "#85dacc",
      "brightCyan": "#9bf1e1"
    }
  },
  {
    "id": "rose-pine",
    "name": "Ros\u00e9 Pine",
    "light": true,
    "bg": "#faf4ed",
    "deep": "#e1dbd5",
    "surface": "#ede7e1",
    "raised": "#f2e9e1",
    "border": "#cecacd",
    "fg": "#575279",
    "muted": "#6e6a86",
    "accent": "#56949f",
    "selection": "#dfdad9",
    "terminal": {
      "background": "#faf4ed",
      "foreground": "#575279",
      "cursor": "#575279",
      "selectionBackground": "#dfdad9",
      "black": "#faf4ed",
      "white": "#575279",
      "brightBlack": "#cecacd",
      "brightWhite": "#575279",
      "red": "#b4637a",
      "brightRed": "#b4637a",
      "green": "#286983",
      "brightGreen": "#286983",
      "yellow": "#ea9d34",
      "brightYellow": "#ea9d34",
      "blue": "#56949f",
      "brightBlue": "#56949f",
      "magenta": "#907aa9",
      "brightMagenta": "#907aa9",
      "cyan": "#d7827e",
      "brightCyan": "#d7827e"
    }
  },
  {
    "id": "solitude",
    "name": "Solitude",
    "light": false,
    "bg": "#101315",
    "deep": "#080a0b",
    "surface": "#0c0e10",
    "raised": "#101315",
    "border": "#4b4e55",
    "fg": "#cacccc",
    "muted": "#cbc2be",
    "accent": "#798186",
    "selection": "#343d41",
    "terminal": {
      "background": "#101315",
      "foreground": "#cacccc",
      "cursor": "#a5aeb4",
      "selectionBackground": "#343d41",
      "black": "#101315",
      "white": "#cacccc",
      "brightBlack": "#4b4e55",
      "brightWhite": "#a5aeb4",
      "red": "#565d60",
      "brightRed": "#de6145",
      "green": "#9fa5a9",
      "brightGreen": "#343d41",
      "yellow": "#d9dbdc",
      "brightYellow": "#c9c2b4",
      "blue": "#798186",
      "brightBlue": "#5d6367",
      "magenta": "#aeaeae",
      "brightMagenta": "#9a9a9a",
      "cyan": "#707070",
      "brightCyan": "#707070"
    }
  },
  {
    "id": "tokyo-night",
    "name": "Tokyo Night",
    "light": false,
    "bg": "#1a1b26",
    "deep": "#0e0e14",
    "surface": "#13141c",
    "raised": "#24283b",
    "border": "#414868",
    "fg": "#a9b1d6",
    "muted": "#b4bee6",
    "accent": "#7aa2f7",
    "selection": "#292e42",
    "terminal": {
      "background": "#1a1b26",
      "foreground": "#a9b1d6",
      "cursor": "#c0caf5",
      "selectionBackground": "#292e42",
      "black": "#1a1b26",
      "white": "#a9b1d6",
      "brightBlack": "#414868",
      "brightWhite": "#c0caf5",
      "red": "#f7768e",
      "brightRed": "#ff7a93",
      "green": "#9ece6a",
      "brightGreen": "#b9f27c",
      "yellow": "#e0af68",
      "brightYellow": "#ff9e64",
      "blue": "#7aa2f7",
      "brightBlue": "#7da6ff",
      "magenta": "#ad8ee6",
      "brightMagenta": "#bb9af7",
      "cyan": "#449dab",
      "brightCyan": "#0db9d7"
    }
  },
  {
    "id": "vantablack",
    "name": "Vantablack",
    "light": false,
    "bg": "#000000",
    "deep": "#070707",
    "surface": "#090909",
    "raised": "#1a1a1a",
    "border": "#7a7a7a",
    "fg": "#ffffff",
    "muted": "#ececec",
    "accent": "#8d8d8d",
    "selection": "#1a1a1a",
    "terminal": {
      "background": "#000000",
      "foreground": "#ffffff",
      "cursor": "#ffffff",
      "selectionBackground": "#1a1a1a",
      "black": "#000000",
      "white": "#ffffff",
      "brightBlack": "#7a7a7a",
      "brightWhite": "#ffffff",
      "red": "#a4a4a4",
      "brightRed": "#a4a4a4",
      "green": "#b6b6b6",
      "brightGreen": "#b6b6b6",
      "yellow": "#cecece",
      "brightYellow": "#cecece",
      "blue": "#8d8d8d",
      "brightBlue": "#8d8d8d",
      "magenta": "#9b9b9b",
      "brightMagenta": "#9b9b9b",
      "cyan": "#b0b0b0",
      "brightCyan": "#b0b0b0"
    }
  },
  {
    "id": "white",
    "name": "White",
    "light": true,
    "bg": "#ffffff",
    "deep": "#e8e8e8",
    "surface": "#f5f5f5",
    "raised": "#c0c0c0",
    "border": "#808080",
    "fg": "#000000",
    "muted": "#000000",
    "accent": "#6e6e6e",
    "selection": "#c0c0c0",
    "terminal": {
      "background": "#ffffff",
      "foreground": "#000000",
      "cursor": "#000000",
      "selectionBackground": "#c0c0c0",
      "black": "#ffffff",
      "white": "#000000",
      "brightBlack": "#808080",
      "brightWhite": "#000000",
      "red": "#2a2a2a",
      "brightRed": "#2a2a2a",
      "green": "#3a3a3a",
      "brightGreen": "#3a3a3a",
      "yellow": "#4a4a4a",
      "brightYellow": "#4a4a4a",
      "blue": "#1a1a1a",
      "brightBlue": "#1a1a1a",
      "magenta": "#2e2e2e",
      "brightMagenta": "#2e2e2e",
      "cyan": "#3e3e3e",
      "brightCyan": "#3e3e3e"
    }
  }
];
const key='boomux.webgpu.theme';
let current=themes[0];
try{current=themes.find(t=>t.id===localStorage.getItem(key))||current;}catch{}
export const getTheme=()=>current;
export const rgba=hex=>[...hex.slice(1).match(/../g).slice(0,3).map(v=>parseInt(v,16)/255),1];
export function terminalTheme(t=current){return {cursorAccent:t.bg,selectionForeground:t.fg,...t.terminal};}
function apply(theme,persist=true){
 current=theme;document.documentElement.dataset.theme=theme.id;
 document.documentElement.style.colorScheme=theme.light?'light':'dark';
 for(const k of ['bg','deep','surface','raised','border','fg','muted','accent','selection'])document.documentElement.style.setProperty(`--ui-${k}`,theme[k]);
 if(persist)try{localStorage.setItem(key,theme.id);}catch{}
 window.dispatchEvent(new Event('boomux-theme'));
}
apply(current,false);
export function mountThemePicker(){
 const trigger=document.querySelector('#theme-picker'),dialog=document.querySelector('#theme-dialog');let candidate=current;
 let showcase=false,suppressCardClick=false,changing=false;
 try{showcase=localStorage.getItem('boomux.webgpu.theme-view')==='showcase';}catch{}
 const view=dialog.querySelector('#theme-view'),cards=dialog.querySelector('.showcase-cards');
 const title=dialog.querySelector('#showcase-name'),position=dialog.querySelector('#showcase-position');
 const list=dialog.querySelector('.theme-list'),preview=dialog.querySelector('.theme-preview'),label=dialog.querySelector('#theme-preview-name');
 function select(t){candidate=t;renderCards();label.textContent=t.name;for(const k of ['bg','surface','fg','muted','accent','border'])preview.style.setProperty(`--preview-${k}`,t[k]);for(const b of list.children){b.setAttribute('aria-pressed',String(b.dataset.theme===t.id));} }

 // Three reusable previews: synthetic Boomux content, never live terminal data.
 for(const offset of [-1,0,1]){
  const card=document.createElement('button');card.type='button';card.className='showcase-card';card.dataset.offset=offset;
  const content=preview.cloneNode(true);content.removeAttribute('style');card.append(content);
  card.onclick=()=>{if(suppressCardClick){suppressCardClick=false;return;}if(offset)step(offset);else dialog.querySelector('#theme-apply').click();};cards.append(card);
 }
 function renderCards(){
  const index=themes.indexOf(candidate);title.textContent=candidate.name;position.textContent=`${String(index+1).padStart(2,'0')} / ${themes.length}`;
  for(const card of cards.children){
   const offset=Number(card.dataset.offset),t=themes[(index+offset+themes.length)%themes.length];
   card.setAttribute('aria-label',offset?`Preview ${t.name}`:`Apply ${t.name}`);
   for(const k of ['bg','surface','fg','muted','accent','border'])card.style.setProperty(`--preview-${k}`,t[k]);
  }
 }
 function setView(){
  dialog.classList.toggle('showcase',showcase);dialog.querySelector('.theme-showcase').hidden=!showcase;
  view.textContent=showcase?'List view':'Showcase';view.setAttribute('aria-pressed',String(showcase));
  renderCards();
 }
 function step(delta){
  select(themes[(themes.indexOf(candidate)+delta+themes.length)%themes.length]);
  if(showcase&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
   for(const animation of cards.getAnimations())animation.cancel();
   cards.animate([{translate:`${delta*55}px 0`,opacity:.45},{translate:'0 0',opacity:1}],{duration:240,easing:'ease-out'});
  }
 }
 view.onclick=()=>{showcase=!showcase;setView();try{localStorage.setItem('boomux.webgpu.theme-view',showcase?'showcase':'list');}catch{}};
 dialog.querySelector('#theme-previous').onclick=()=>step(-1);
 dialog.querySelector('#theme-next').onclick=()=>step(1);
 let touchStart=null;
 cards.addEventListener('pointerdown',e=>{suppressCardClick=false;if(e.pointerType==='touch')touchStart=e.clientX;});
 cards.addEventListener('pointerup',e=>{if(touchStart!==null){const dx=e.clientX-touchStart;touchStart=null;if(Math.abs(dx)>45){suppressCardClick=true;step(dx<0?1:-1);e.preventDefault();}}});
 cards.addEventListener('pointercancel',()=>{touchStart=null;});
 setView();
 for(const t of themes){const b=document.createElement('button');b.type='button';b.dataset.theme=t.id;b.className='theme-choice';b.setAttribute('aria-pressed','false');
 const swatches=document.createElement('span');swatches.className='theme-swatches';swatches.setAttribute('aria-hidden','true');for(const color of [t.bg,t.surface,t.fg,t.accent]){const dot=document.createElement('i');dot.style.background=color;swatches.append(dot);}
 b.append(swatches,document.createTextNode(t.name));b.onclick=()=>select(t);list.append(b);}
 trigger.onclick=()=>{if(changing)return;document.querySelector('#settings').open=false;select(current);dialog.showModal();(showcase?dialog.querySelector('#theme-next'):list.querySelector(`[data-theme="${current.id}"]`)).focus();};
 dialog.querySelector('#theme-apply').onclick=()=>{
  if(changing)return;
  const selected=candidate;
  if(selected===current){dialog.close();return;}
  const commit=()=>{apply(selected);dialog.close();};
  const motion=!matchMedia('(prefers-reduced-motion: reduce)').matches&&document.querySelector('#motion')?.checked!==false;
  if(!motion||!document.startViewTransition||document.hidden){commit();return;}
  changing=true;document.documentElement.classList.add('theme-wiping');
  const cleanup=()=>{changing=false;document.documentElement.classList.remove('theme-wiping');};
  try{
   const transition=document.startViewTransition(commit);
   transition.ready.catch(()=>{}); // A skipped animation still applies the theme.
   transition.finished.then(cleanup,cleanup);
  }catch{cleanup();commit();}
 };
 dialog.querySelector('#theme-cancel').onclick=()=>dialog.close();
 dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 dialog.addEventListener('close',()=>trigger.focus());
 dialog.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();step(e.key==='ArrowRight'?1:-1);if(!showcase)list.querySelector(`[data-theme="${candidate.id}"]`).focus();}});
 if(new URLSearchParams(location.search).has('theme-showcase')){showcase=true;setView();trigger.click();}
 window.addEventListener('storage',e=>{if(e.key===key){const t=themes.find(t=>t.id===e.newValue);if(t)apply(t,false);}});
}
